### ISSUE TITLE
アラート（枠線ボックス）の改善案検討・テスト

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1551]
アラート系は非常によく使うのでもっと簡単に使えるようにする手段を検討したい。
まずは、必要なレイアウトと、既存のブロック＋CSSでいけるのか試してみる

■ 枠線ボックスブロック + CSSグリッドなどを使ってアラートてきなレイアウトが作れるかテスト

■ 他のテーマなどに実装されているアラートブロックなどを参考に、アラート向けのレイアウトをパターンで作ってみる

参考
```
<!-- wp:group {"className":"is-style-vk-group-alert-warning","layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-vk-group-alert-warning"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"50px"} -->
<div class="wp-block-column" style="flex-basis:50px"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:vk-blocks/icon {"faIcon":"\u003ci class=\u0022fas fa-exclamation-triangle\u0022\u003e\u003c/i\u003e","iconSize":24,"iconMargin":0,"iconRadius":0,"iconAlign":"center","iconType":"2","iconColor":"#bd8c06"} -->
<div class="wp-block-vk-blocks-icon vk_icon"><div class="vk_icon_frame text-center is-style-noline"><div class="vk_icon_border has-text-color" style="color:#bd8c06;width:calc(24px + 0px);height:calc(24px + 0px);border-radius:0%"><i style="font-size:24px" class="fas vk_icon_font fa-exclamation-triangle"></i></div></div></div>
<!-- /wp:vk-blocks/icon -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Point</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"90%"} -->
<div class="wp-block-column" style="flex-basis:90%"><!-- wp:group {"style":{"border":{"left":{"color":"#c9960b"}},"spacing":{"padding":{"left":"var:preset|spacing|40"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-left-color:#c9960b;padding-left:var(--wp--preset--spacing--40)"><!-- wp:paragraph -->
<p>この記事は Lightning 15.4 以降でのみ有効です。最新版にアップデートしてご確認ください。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

**Comment by doshimaf** [comment]
@kurudrive 
枠線ボックスブロック + CSSグリッドでアラートパターンを作ってみました。

<img width="789" alt="スクリーンショット 2023-01-26 11 35 08" src="https://user-images.githubusercontent.com/73574599/214745662-ff416f45-9eac-4120-8ee8-f9d5c9ef796c.png">

①画像上のパターン
```
<!-- wp:vk-blocks/border-box {"borderColor":"luminous-vivid-amber","faIcon":"\u003ci class=\u0022fas fa-exclamation-triangle\u0022\u003e\u003c/i\u003e","vkbCustomCss":"selector {\n  display: grid;\n  grid-template-columns: 1fr 6fr;\n    align-items: center;\n    justify-content: center;\n}selector \u003e .vk_borderBox_title_container {\n  display: flex !important;\n  flex-wrap: wrap;\n  justify-content: center;\n  align-content: center;\n  height: 100%;\n  padding: .5em;\n  border-radius: 3px 0 0 3px;\n}\nselector \u003e .vk_borderBox_title_container .vk_borderBox_title {\n  width: 100%;\n  margin-bottom: 0;\n  text-align: center;\n}\nselector \u003e .vk_borderBox_title_container i {\n  margin: 0 auto !important;\n  font-size: 24px;\n}\nselector \u003e .vk_borderBox_body{\n    padding: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dspacing\u002d\u002d30);\n  border-radius: 0 3px 3px 0;\n}","className":"is-style-vk_borderBox-style-solid-kado-tit-tab vk_custom_css"} -->
<div class="wp-block-vk-blocks-border-box vk_borderBox vk_borderBox-background-transparent has-text-color has-luminous-vivid-amber-color is-style-vk_borderBox-style-solid-kado-tit-tab vk_custom_css"><div class="vk_borderBox_title_container has-background has-luminous-vivid-amber-background-color"><i class="fas fa-exclamation-triangle"></i><h4 class="vk_borderBox_title">Point</h4></div><div class="vk_borderBox_body"><!-- wp:paragraph -->
<p>この記事は Lightning 15.4 以降でのみ有効です。最新版にアップデートしてご確認ください。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:vk-blocks/border-box -->
```

②画像下のパターン
```
<!-- wp:vk-blocks/border-box {"borderColor":"#bd8c06","faIcon":"\u003ci class=\u0022fas fa-exclamation-triangle\u0022\u003e\u003c/i\u003e","vkbCustomCss":"selector {\n  display: grid;\n  grid-template-columns: 1fr 6fr;\n  align-items: center;\n  justify-content: center;\n  background-color: #fcf8e3 !important;\n  border: 1px solid #faebcc !important;\n  border-radius: 3px;\n}\nselector \u003e .vk_borderBox_title_container {\n  display: flex !important;\n  flex-wrap: wrap;\n  justify-content: center;\n  align-content: center;\n  height: 100%;\n  padding: .5em;\n  background-color: initial !important;\n  color: inherit;\n}\nselector \u003e .vk_borderBox_title_container \u003e .vk_borderBox_title {\n  width: 100%;\n  margin-bottom: 0;\n  text-align: center;\n}\nselector \u003e .vk_borderBox_title_container \u003e i {\n  margin: 0 auto !important;\n  font-size: 24px;\n}\nselector \u003e .vk_borderBox_body{\n  padding: 0 var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dspacing\u002d\u002d30);\n  margin: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dspacing\u002d\u002d30) 0;\n  border: none;\n  border-left: 1.5px solid #bd8c06;\n}\nselector \u003e .vk_borderBox_body \u003e p {\n  color: #8a6d3b !important;\n}","className":"vk_custom_css is-style-vk_borderBox-style-solid-kado-tit-tab"} -->
<div class="wp-block-vk-blocks-border-box vk_borderBox vk_borderBox-background-transparent has-text-color vk_custom_css is-style-vk_borderBox-style-solid-kado-tit-tab" style="color:#bd8c06"><div class="vk_borderBox_title_container has-background" style="background-color:#bd8c06"><i class="fas fa-exclamation-triangle"></i><h4 class="vk_borderBox_title">Point</h4></div><div class="vk_borderBox_body"><!-- wp:paragraph -->
<p>この記事は Lightning 15.4 以降でのみ有効です。最新版にアップデートしてご確認ください。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:vk-blocks/border-box -->
```


> ■ 枠線ボックスブロック + CSSグリッドなどを使ってアラートてきなレイアウトが作れるかテスト

引き続き他のパターンも考えてみますが、確認をお願いたします。

また、枠線ブロックで作ってみたところ、アラートブロックで作るよりカスタムCSSで細かな調整をしやすいかなと思いました。

**Comment by kurudrive** [comment]
@doshimaf ありがとうございます！

まずは僕もこの２つがあれば事足りるかなと思いますが、まだ他に需要が高そうなのがあれば引き続きよろしくお願いするとして、とりあえず第一弾として、上記デザインについて、
カスタムブロックスタイルに登録すれば使える というCSSを作ってください
（上の画面があるという事はほぼ出来てる気がしますが）

※言うまでもなく月曜以降の対応で可

**Comment by doshimaf** [comment]
@kurudrive 

一番上の階層の枠線ブロックに指定したCSSはこちらです。

どちらもスタイルは「直角 ピン角 タブ」です。
１つ目の方は色に「明るく鮮やかな琥珀」を使用しています。


```css
/* アイコン背景色有り */
selector {
  display: grid;
  grid-template-columns: 1fr 6fr;
    align-items: center;
    justify-content: center;
}selector > .vk_borderBox_title_container {
  display: flex !important;
  flex-wrap: wrap;
  justify-content: center;
  align-content: center;
  height: 100%;
  padding: .5em;
  border-radius: 3px 0 0 3px;
}
selector > .vk_borderBox_title_container .vk_borderBox_title {
  width: 100%;
  margin-bottom: 0;
  text-align: center;
}
selector > .vk_borderBox_title_container i {
  margin: 0 auto !important;
  font-size: 24px;
}
selector > .vk_borderBox_body{
    padding: var(--wp--preset--spacing--30);
  border-radius: 0 3px 3px 0;
}
```

```css
/* 全体背景色 */
selector {
  display: grid;
  grid-template-columns: 1fr 6fr;
  align-items: center;
  justify-content: center;
  background-color: #fcf8e3 !important;
  border: 1px solid #faebcc !important;
  border-radius: 3px;
}
selector > .vk_borderBox_title_container {
  display: flex !important;
  flex-wrap: wrap;
  justify-content: center;
  align-content: center;
  height: 100%;
  padding: .5em;
  background-color: initial !important;
  color: #bd8c06;
}
selector > .vk_borderBox_title_container > .vk_borderBox_title {
  width: 100%;
  margin-bottom: 0;
  text-align: center;
}
selector > .vk_borderBox_title_container > i {
  margin: 0 auto !important;
  font-size: 24px;
}
selector > .vk_borderBox_body{
  padding: 0 var(--wp--preset--spacing--30);
  margin: var(--wp--preset--spacing--30) 0;
  border: none;
  border-left: 1.5px solid #bd8c06;
}
selector > .vk_borderBox_body > p {
  color: #8a6d3b !important;
}
```
